version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\SimpleGitVersion\SGV-Net
branches:
  only:
    - master
    - develop
environment:
  MYGET_PREVIEW_API_KEY:
    secure: CfEqNYjhrGX9DyalZ4jcadzJ/x8q25GulMCbZQDRRs+XetfHn2AEP79OJXE1wSJ8
  MYGET_CI_API_KEY:
    secure: z3ZFnSM3FPCaJYkLhqjZmFTCw1Wf1hmRznQ0/UfxY/5haxctmymvFhh+PTz+/eHw
  MYGET_RELEASE_API_KEY:
    secure: BmENGV1y8uv5cLhMhwpoDLwQiLJh4C66c53+FW8FuuVfu5Lf4Ac6NvSuqO/1MbPm
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
