<?xml version="1.0" encoding="utf-8"?>

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="RunSimpleGitVersion" BeforeTargets="BeforeCompile;CoreCompile;GenerateNuspec">

        <PropertyGroup>
            <SimpleGitVersionFileExe>dotnet &quot;$(MSBuildThisFileDirectory)SimpleGitVersion.Core.dll&quot;</SimpleGitVersionFileExe>
        </PropertyGroup>
        <!-- The working directory is by default the project directory. No need to specify it. -->
        <Exec Command="$(GitVersionFileExe) --out-dir &quot;$(BaseIntermediateOutputPath)&quot;" />
    </Target>
    
</Project>
