<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Minimal Simple Git Version abstraction that enables to reason on new versions and configure a build.</Description>
        <PackageTags>Versioning, SemVer, NuGet, CSemVer, InformationalVersion, Build</PackageTags>
        <Nullable>enable</Nullable>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CSemVer" Version="13.0.0-r" />
    </ItemGroup>
</Project>